export const movies = [
  {
    "maPhim": 10530,
    "tenPhim": "KẺ ĐỘC HÀNH",
    "biDanh": "ke-doc-hanh",
    "trailer": "https://youtu.be/_iyC2aUCxY0",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/ke-doc-hanh_gp09.jpg",
    "moTa": "Bộ phim sẽ được phát sóng dự kiến vào tháng 10/2022 Với 08 tập phim theo dạng web series, cùng sự góp mặt với hơn 30 nghệ sỹ, diễn viên… Với chi phí đầu tư lớn và được phát sóng trên nền tảng VOD. Ai Chết Giơ Tay (new season) với tên gọi Kẻ Độc Hành. Đây là dự án tâm huyết của Lập đã được chuẩn bị hơn 1 năm, đã được bấm máy vào tháng 05/2021 tại Long Xuyên AG (quê nhà của Lập) và sẽ được hậu kỳ hơn 1 năm.",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-11-05T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 10531,
    "tenPhim": "Nhà Bà Nữ",
    "biDanh": "nha-ba-nu",
    "trailer": "https://www.youtube.com/watch?v=1anBxcsV5b8",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/nha-ba-nu_gp09.jpg",
    "moTa": "Ông Thái là một cảnh sát về hưu nhưng không chịu an phận thủ thường, hàng ngày vẫn đi tìm bắt tội phạm vặt trong xóm cho đỡ nhớ nghề. Một ngày kia, Hoàng - tên trùm ma túy mới ra tù bỗng dưng chuyển đến xóm ông và mở một văn phòng bất động sản. Nghi ngờ đây là nơi làm ăn phi pháp, ông Thái quyết định âm thầm điều tra. Ông mua lại tiệm cơm tấm đối diện trụ sở của Hoàng để làm nơi theo dõi, đồng thời thu nạp Thu - Phú - Vinh - Mèo, đám thanh niên “bất hảo” trong xóm về quán hỗ trợ buôn bán để rảnh tay \"phá án\". Trớ trêu thay, tiệm cơm bất ngờ nổi tiếng và ăn nên làm ra, khiến cho \"chuyên án đặc biệt\" của ông đứng trước nguy cơ đổ bể.",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-05-28T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 10532,
    "tenPhim": "Tăng tốc phía em",
    "biDanh": "tang-toc-phia-em",
    "trailer": "https://www.youtube.com/watch?v=h261_whvLPM",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/tang-toc-phia-em_gp09.jpg",
    "moTa": "Kao (Nat Kitcharit) là một nhà vô địch thế giới môn xếp ly tốc độ (Speed Stack). Tuy thành công và nổi tiếng nhưng Kao lại chỉ như một đứa trẻ to xác suốt ngày chỉ ăn, ngủ và tập luyện. Mọi vấn đề xung quanh anh đều một tay Jay (Yaya) bạn gái anh quán xuyến. Đến một ngày khi Jay quyết định chia tay thì Kao như bị mất tất cả. Anh phải bắt đầu học những kỹ năng sống cơ bản để có thể tự sống một mình và chăm sóc bản thân. Song song đó những đối thủ mới cũng xuất hiện và đe dọa đến vị trí quán quân của Kao.",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-05-11T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 10533,
    "tenPhim": "Phim cực kì hay",
    "biDanh": "phim-cuc-ki-hay",
    "trailer": "https://youtu.be/3xccmeAsy8g",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/aaaaaaaaaaaaaaa_gp09.jpg",
    "moTa": "Phim hay, nên đừng đổi mô tả nữa",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-08-26T19:12:55.477",
    "danhGia": 10
  },
  {
    "maPhim": 10606,
    "tenPhim": "Nghề siêu dễ",
    "biDanh": "nghe-sieu-de",
    "trailer": "https://www.youtube.com/watch?v=ZOgNsZpLwvs",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/aaaaaaaaaaa_gp09.jpg",
    "moTa": "https://www.youtube.com/watch?v=ZOgNsZpLwvshttps://www.youtube.com/watch?v=ZOgNsZpLwvshttps://www.youtube.com/watch?v=ZOgNsZpLwvshttps://www.youtube.com/watch?v=ZOgNsZpLwvs",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-05-15T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 10614,
    "tenPhim": "RỪNG SĂN NGƯỜI",
    "biDanh": "rung-san-nguoi",
    "trailer": "https://www.youtube.com/watch?v=BRXHdMcU_co",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/rung-san-nguoi_gp09.jpg",
    "moTa": "Một biệt đội được phái vào rừng sâu để tìm tài liệu tuyệt mật và những người đồng đội mất tích. Nhưng mọi thứ không đơn giản như thế, họ đã tiến vào một vùng đất chất, nơi quỷ dữ thống trị và điều khiển mọi thứ. Đặc biệt, phim có sự góp mặt của Mickey Rourke, phản diện chính từ Iron Man 2.",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-05-17T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 10647,
    "tenPhim": "Black Adam",
    "biDanh": "black-adam",
    "trailer": "https://www.youtube.com/watch?v=N73oTiIIJe0",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/black-adam_gp09.jpeg",
    "moTa": "Mặc dù kế hoạch là Black Adam sẽ xuất hiện trong Shazam 2, thế nhưng nhà sản xuất quyết định cho nhân vật này ra một phần phim riêng. Black Adam là một pháp sư Ai Cập cổ đại được chọn làm người kế thừa sức mạnh Shazam tuy nhien hắn dần dần bị tha hoá về đạo đức và sự lạm dụng sức mạnh của mình. Chính vì vậy hắn đã bị phong ấn suốt mấy ngàn năm qua.",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2023-04-29T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 10649,
    "tenPhim": "Captain Marvel 2",
    "biDanh": "captain-marvel-2",
    "trailer": "https://www.youtube.com/watch?v=M3tBP1MyMB0",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/captain-marvel-2_gp09.jpeg",
    "moTa": "Diễn ra trong bối cảnh hiện đại sau những năm 1990 vintage của bộ phim gốc, Captain Marvel 2 sẽ tiếp nối sau sự kiện Avenger: Endgame với kịch bản được viết bởi Megan McDonnel (một trong những nhà biên kịch WandaVision). Chúng ta có thể tin rằng Carol Danvers sẽ được cách tân phù hợp với gam màu MCU hiện tại trong Captain Marvel 2.",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-05-26T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 10765,
    "tenPhim": "iron man 4",
    "biDanh": "iron-man-4",
    "trailer": "https://www.youtube.com/embed/SwwlFvOwkhA",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/iron-man-4_gp09.jpg",
    "moTa": "mota ironman",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-07-01T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 10766,
    "tenPhim": "Thor 5",
    "biDanh": "thor-5",
    "trailer": "https://www.youtube.com/embed/TyfBgQKsEXs",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/thor-5_gp09.jpg",
    "moTa": "than sam 5 hihihihihihiih hiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\nhiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-07-03T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 10786,
    "tenPhim": "test1",
    "biDanh": "test1",
    "trailer": "https://www.youtube.com/watch?v=M3tBP1MyMB0",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/test1_gp09.png",
    "moTa": "Test",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-07-11T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 10840,
    "tenPhim": "Detective Pikachu",
    "biDanh": "detective-pikachu",
    "trailer": "https://www.youtube.com/embed/1roy4o4tqQM",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/detective-pikachu_gp09.jpg",
    "moTa": "Good Pokemon: Detective Pikachu xoay quay hành trình truy tìm manh mối phá án về cái chết của Harry Goodman – thám tử mẫn cán ở thành phố Ryme của Tim Goodman và người bạn đồng hành siêu đáng yêu Pikachu. Là người duy nhất nghe được giọng nói thực của của Pikachu thay vì tiếng “Pika Pika” quen thuộc, Tim và Pikachu nhanh chóng trở thành bạn thân và cùng dấn thân vào cuộc điều tra những vụ mất tích bí ẩn trong thành phố. Trong hành trình phá án, cặp đôi “oan gia” này đã gây ra những tình huống trái ngang nhưng tràn đầy tiếng cười.",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-11-07T00:00:00",
    "danhGia": 9
  },
  {
    "maPhim": 10949,
    "tenPhim": "evfweagwag",
    "biDanh": "evfweagwag",
    "trailer": "https://www.youtube.com/watch?v=AghIqOvlxRQ",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/evfweagwag_gp09.jpg",
    "moTa": "aaa...",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-10-02T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 10952,
    "tenPhim": "TẤM VÉ ĐẾN THIÊN ĐƯỜNG",
    "biDanh": "tam-ve-den-thien-duong",
    "trailer": "https://www.youtube.com/watch?v=pyYq_iGzetM",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/tam-ve-den-thien-duong_gp09.jpg",
    "moTa": "Hai diễn viên kỳ cựu của Hollywood - George Clooney và Julia Roberts sẽ tái hợp trên màn ảnh rộng trong vai đôi vợ chồng đã li hôn, nhưng lại cùng chung sứ mệnh ngăn cản cuộc kết hôn của đứa con gái yêu. Bởi họ sợ rằng con gái đang mắc phải sai lầm tương tự điều mà họ đã từng trải qua. Ticket to Paradise là một bộ phim hài lãng mạn về sự ngọt ngào bất ngờ của \"cơ hội thứ hai”.",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-10-14T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 10953,
    "tenPhim": "21312TẤM VÉ ĐẾN THIÊN ĐƯỜN",
    "biDanh": "21312tam-ve-den-thien-duon",
    "trailer": "https://www.youtube.com/watch?v=pyYq_iGzetM",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/21312tam-ve-den-thien-duon_gp09.jpg",
    "moTa": "Hai diễn viên kỳ cựu của Hollywood - George Clooney và Julia Roberts sẽ tái hợp trên màn ảnh rộng trong vai đôi vợ chồng đã li hôn, nhưng lại cùng chung sứ mệnh ngăn cản cuộc kết hôn của đứa con gái yêu. Bởi họ sợ rằng con gái đang mắc phải sai lầm tương tự điều mà họ đã từng trải qua. Ticket to Paradise là một bộ phim hài lãng mạn về sự ngọt ngào bất ngờ của \"cơ hội thứ hai”.\r\n",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-10-14T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 10984,
    "tenPhim": "Aquaman",
    "biDanh": "aquaman",
    "trailer": "https://www.youtube.com/embed/YmHijIQrOiY",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/aquaman_gp09.jpg",
    "moTa": "Aquaman and the Lost Kingdom is an upcoming American superhero film based on the DC Comics character Aquaman. Produced by DC Films, The Safran Company, and Atomic Monster Productions, and set for distribution by Warner Bros. Pictures, it is intended to be the sequel to Aquaman (2018) and the thirteenth film in the DC Extended Universe (DCEU). The film is directed by James Wan from a screenplay written by David Leslie Johnson-McGoldrick, and stars Jason Momoa as Arthur Curry / Aquaman alongside Amber Heard, Willem Dafoe, Patrick Wilson, Dolph Lundgren, Yahya Abdul-Mateen II, Temuera Morrison, and Nicole Kidman.\r\n\r\nMomoa pitched a story for an Aquaman sequel during production of the first film. Wan did not want to rush a sequel but agreed in January 2019 to oversee development. Johnson-McGoldrick signed to write the screenplay a month later, and Wan was confirmed to be directing in August 2020. He said the film would expand on Aquaman's worldbuilding, and announced the sequel's title in June 2021. Filming began at the end of the month and concluded in January 2022, taking place in the United Kingdom, Hawaii, and Los Angeles.\r\n",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-11-07T23:04:38.213",
    "danhGia": 10
  },
  {
    "maPhim": 10985,
    "tenPhim": "cô gái từ quá khứ ",
    "biDanh": "co-gai-tu-qua-khu",
    "trailer": "https://www.youtube.com/watch?v=WsBV9s1SqpM",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/co-gai-tu-qua-khu_gp09.png",
    "moTa": "Đang tất bật chuẩn bị cho đám cưới triệu đô cùng chàng Jack điển trai, đại mỹ nhân showbiz Ms. Q/Hoàng Quyên (Ninh Dương Lan Ngọc) bất ngờ mất tích một cách bí ẩn ngay sau khi gặp lại Quỳnh Yên (Kaity Nguyễn), một người bạn đã mất liên lạc từ 15 năm trước. Ngay lập tức, các rắc rối liên tục ập đến, kéo theo những bí mật đen tối của cả hai dần bị lột trần. Ai là kẻ thủ ác? Ai mới là nạn nhân? P/S: Bất kể cô ta có nói gì thì cũng nên nhớ: Đừng tin lời cô ta nói!",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-10-24T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 10986,
    "tenPhim": "black Adam",
    "biDanh": "black-adam",
    "trailer": "https://www.youtube.com/watch?v=uAop-vMrggI",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/black-adam_gp09.jpg",
    "moTa": "Dwayne Johnson sẽ góp mặt trong tác phẩm hành động - phiêu lưu mới của New Line Cinema “Black Adam”. Đây là bộ phim đầu tiên trên màn ảnh rộng khai thác câu chuyện của siêu anh hùng DC này, dưới sự sáng tạo của đạo diễn Jaume Collet-Serra (“Jungle Cruise”). \r\n\r\nGần 5.000 năm sau khi bị cầm tù với quyền năng tối thượng từ những vị thần cổ đại, Black Adam (Dwayne Johnson) sẽ được giải phóng khỏi nấm mồ chết chóc của mình, mang tới thế giới hiện đại một kiểu nhận thức về công lý hoàn toàn mới. \r\n\r\nBên cạnh Johnson, phim quy tụ dàn sao Aldis Hodge (“City on a Hill,” “One Night in Miami”) trong vai Hawkman, Noah Centineo (“To All the Boys I’ve Loved Before”) trong vai Atom Smasher, Sarah Shahi (“Sex/Life”, “Rush Hour 3”) trong vai Adrianna, Marwan Kenzari (“Murder on the Orient Express”, “The Mummy”) trong vai Ishmael, Quintessa Swindell (“Voyagers”, “Trinkets”) trong vai Cyclone, Bodhi Sabongui (“A Million Little Things”) trong vai Amon, và Pierce Brosnan (“Mamma Mia!” và loạt phim James Bond) trong vai Dr. Fate.\r\n\r\nCollet-Serra đạo diễn dựa trên kịch bản do Adam Sztykiel và Rory Haines & Sohrab Noshirvani chấp bút, với cốt truyện sáng tạo bởi Adam Sztykiel và Rory Haines & Sohrab Noshirvani, dựa trên nhân vật thuộc vũ trụ DC Black Adam sáng tạo bởi Bill Parker cùng C.C. Beck. Đội ngũ sản xuất phim bao gồm Beau Flynn, Dwayne Johnson, Hiram Garcia và Dany Garcia, cùng với Richard Brener, Walter Hamada, Dave Neustadter, Chris Pan, Eric McLeod, Geoff Johns và Scott Sheldon.\r\n\r\n“Black Adam” dự kiến sẽ công phá phòng vé  từ ngày 21.10.2022 với định dạng 2D và IMAX. Phim được phân phối toàn cầu bởi hàng Warner Bros. Pictures.",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-10-25T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 10987,
    "tenPhim": "Fantastic Beast",
    "biDanh": "fantastic-beast",
    "trailer": "https://www.youtube.com/embed/Y9dr2zw-TXQ",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/fantastic-beast_gp09.jpg",
    "moTa": "Warner Bros. Pictures’ “Fantastic Beasts: The Secrets of Dumbledore” is the newest adventure in the Wizarding World™ created by J.K. Rowling.\r\n\r\nProfessor Albus Dumbledore (Jude Law) knows the powerful Dark wizard Gellert Grindelwald (Mads Mikkelsen) is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts Magizoologist Newt Scamander (Eddie Redmayne) to lead an intrepid team of wizards, witches and one brave Muggle baker on a dangerous mission, where they encounter old and new beasts and clash with Grindelwald’s growing legion of followers. But with the stakes so high, how long can Dumbledore remain on the sidelines?\r\n\r\nThe film features an ensemble cast led by Oscar winner Eddie Redmayne (“The Theory of Everything”), two-time Oscar nominee Jude Law (“Cold Mountain,” “The Talented Mr. Ripley”), Ezra Miller, Dan Fogler, Alison Sudol, Callum Turner, Jessica Williams, Katherine Waterston, and Mads Mikkelsen.\r\n\r\n“Fantastic Beasts: The Secrets of Dumbledore” was directed by David Yates, from a screenplay by J.K. Rowling & Steve Kloves, based upon a screenplay by J.K. Rowling. The film was produced by David Heyman, J.K. Rowling, Steve Kloves, Lionel Wigram and Tim Lewis. Neil Blair, Danny Cohen, Josh Berger, Courtenay Valenti and Michael Sharp served as executive producers.\r\n\r\nThe film’s behind-the-scenes creative team included director of photography George Richmond (“Rocketman,” “Kingsman: The Golden Circle”), three-time Oscar-winning production designer Stuart Craig (“The English Patient,” “Dangerous Liaisons,” “Gandhi,” the “Harry Potter” and “Fantastic Beasts” films) and production designer Neil Lamont (“Solo: A Star Wars Story,” “Rogue One: A Star Wars Story”), four-time Oscar-winning costume designer Colleen Atwood (“Chicago,” “Memoirs of a Geisha,” “Alice in Wonderland,” “Fantastic Beasts\r\nand Where to Find Them”), and Yates’ longtime editor Mark Day (“Fantastic Beasts: The Crimes of Grindelwald,” the last four “Harry Potter” films). The music is by nine-time Oscar nominee James Newton Howard (“News of the World,” “Fantastic Beasts: The Crimes of Grindelwald,” “Defiance,” “Michael Clayton,” “The Hunger Games” films).\r\n\r\nWarner Bros. Pictures presents a Heyday Films Production, a David Yates film, “Fantastic Beasts: The Secrets of Dumbledore,” in theaters internationally beginning 7 April 2022 and in North America on April 15, 2022. The film will be distributed worldwide in select theatres and IMAX by Warner Bros. Pictures.",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-11-07T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 10988,
    "tenPhim": "Phim chữ A",
    "biDanh": "phim-chu-a",
    "trailer": "https://www.youtube.com/watch?v=pyYq_iGzetM",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/phim-chu-a_gp09.jpg",
    "moTa": "a",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-09-29T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 10989,
    "tenPhim": "BỖNG DƯNG TRÚNG SỐ",
    "biDanh": "bong-dung-trung-so",
    "trailer": "https://www.youtube.com/embed/D3KbO3QF-lg",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/bong-dung-trung-so_gp09.png",
    "moTa": "Người lính Hàn Quốc Chun Woo (Ko Kyoung-pyo) vô tình nhặt được tờ vé số trúng độc đắc trị giá lên đến gần 6 triệu đô! Nhưng chưa kịp vui mừng bao lâu, tờ vé số ấy không may bị cuốn bay sang bên kia biên giới và rơi vào tay anh lính Triều Tiên Yong Ho (Lee Yi-kyung). Chun Woo cần tờ vé số để đổi tiền, trong khi Yong Ho dù nắm giữ tờ vé quan trọng lại không thể đặt chân đến Hàn Quốc. Câu chuyện ngày càng trở nên rắc rối và hài hước khi có thêm những người đồng đội của hai anh chàng biết được sự việc và nhất quyết tham gia vào cuộc đàm phán chia tiền.",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-11-07T23:03:34.007",
    "danhGia": 10
  },
  {
    "maPhim": 11231,
    "tenPhim": "Lật Mặt 6: Tấm Vé Định Mệnh",
    "biDanh": "lat-mat-6-tam-ve-dinh-menh",
    "trailer": "https://www.youtube.com/watch?v=DeZGe5pHRQY",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/lat-mat-6-tam-ve-dinh-menh_gp09.jpg",
    "moTa": "Một nhóm bạn thân lâu năm bất ngờ nhận được cơ hội đổi đời khi biết tấm vé của cả nhóm trúng giải độc đắc 136.8 tỷ. Đột nhiên An, người nắm giữ tấm vé bất ngờ gặp tai nạn không qua khỏi. Đứng trước món tiền trúng số đáng mơ ước lẽ ra sẽ dễ dàng có được trong tầm tay, nhóm bạn bước chân vào hành trình đi tìm tờ vé số. Nhưng đó chỉ là khởi đầu của vô số những sự kiện không ngờ đến. Liệu hành trình tìm kiếm và chia chác món tiền trong mơ béo bở này sẽ thực sự dẫn đưa cả nhóm đến đâu?",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2023-05-10T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 11244,
    "tenPhim": "prison break",
    "biDanh": "prison-break",
    "trailer": "https://www.youtube.com/watch?v=M3tBP1MyMB0",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/prison-break_gp09.jpg",
    "moTa": "abc",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2023-05-17T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 11256,
    "tenPhim": "Chuộc lại",
    "biDanh": "chuoc-lai",
    "trailer": "https://www.youtube.com/watch?v=H_EW3U7HlH0",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/chuoc-lai_gp09.jpg",
    "moTa": "Bị đưa vào con đường mại dâm từ khi còn nhỏ, Angel không biết gì ngoài sự phản bội. Trái tim của cô ấy liệu còn có thể được hàn gắn?",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2023-06-05T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 11387,
    "tenPhim": "John-Cena",
    "biDanh": "john-cena",
    "trailer": "https://www.youtube.com/watch?v=kvAfmYNtugQ",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/john-cena_gp09.jpg",
    "moTa": "Good...",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2025-01-01T00:00:00",
    "danhGia": 2
  },
  {
    "maPhim": 11388,
    "tenPhim": "string",
    "biDanh": "string",
    "trailer": "string",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/string_gp09.jpg",
    "moTa": "string",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2025-01-01T00:00:00",
    "danhGia": 0
  },
  {
    "maPhim": 11389,
    "tenPhim": "string",
    "biDanh": "string",
    "trailer": "string",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/string_gp09.jpg",
    "moTa": "string",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2025-01-01T00:00:00",
    "danhGia": 0
  },
  {
    "maPhim": 11390,
    "tenPhim": "stringx",
    "biDanh": "stringx",
    "trailer": "string",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/stringx_gp09.jpg",
    "moTa": "string",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2025-01-01T00:00:00",
    "danhGia": 0
  },
  {
    "maPhim": 11391,
    "tenPhim": "stringx",
    "biDanh": "stringx",
    "trailer": "string",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/stringx_gp09.jpg",
    "moTa": "string",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2025-01-01T00:00:00",
    "danhGia": 0
  },
  {
    "maPhim": 11392,
    "tenPhim": "stringxx",
    "biDanh": "stringxx",
    "trailer": "string",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/stringxx_gp09.jpg",
    "moTa": "string",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2025-01-01T00:00:00",
    "danhGia": 0
  },
  {
    "maPhim": 11393,
    "tenPhim": "strinxg",
    "biDanh": "strinxg",
    "trailer": "string",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/strinxg_gp09.jpg",
    "moTa": "string",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-02-22T00:00:00",
    "danhGia": 0
  },
  {
    "maPhim": 11394,
    "tenPhim": "strinxgxx",
    "biDanh": "strinxgxx",
    "trailer": "string",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/strinxgxx_gp09.jpg",
    "moTa": "string",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2025-01-01T00:00:00",
    "danhGia": 0
  },
  {
    "maPhim": 11395,
    "tenPhim": "strinxgxx",
    "biDanh": "strinxgxx",
    "trailer": "string",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/strinxgxx_gp09.jpg",
    "moTa": "string",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2025-01-01T00:00:00",
    "danhGia": 0
  },
  {
    "maPhim": 11396,
    "tenPhim": "John Bold",
    "biDanh": "john-bold",
    "trailer": "https://www.youtube.com/watch?v=9O24MDSSxt8",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/john-bold_gp09.jpg",
    "moTa": "a",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2023-10-27T00:00:00",
    "danhGia": 10
  },
  {
    "maPhim": 11397,
    "tenPhim": "strinxgxxx",
    "biDanh": "strinxgxxx",
    "trailer": "string",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/strinxgxxx_gp09.jpg",
    "moTa": "string",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2025-01-01T00:00:00",
    "danhGia": 0
  },
  {
    "maPhim": 11398,
    "tenPhim": "strinxgxxx",
    "biDanh": "strinxgxxx",
    "trailer": "string",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/strinxgxxx_gp09.jpg",
    "moTa": "string",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2025-01-01T00:00:00",
    "danhGia": 0
  },
  {
    "maPhim": 11399,
    "tenPhim": "strinxgxxx x",
    "biDanh": "strinxgxxx-x",
    "trailer": "string",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/strinxgxxx-x_gp09.jpg",
    "moTa": "string",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2025-01-01T00:00:00",
    "danhGia": 0
  },
  {
    "maPhim": 11402,
    "tenPhim": "John Film",
    "biDanh": "john-film",
    "trailer": "https://www.youtube.com/watch?v=-OQYBmGySJQ",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/john-film_gp09.jpg",
    "moTa": "https://htsport.vn/wp-content/uploads/2020/03/champions-league-la-gi-1.jpg",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2023-10-26T00:00:00",
    "danhGia": 9
  },
  {
    "maPhim": 11404,
    "tenPhim": "Remix",
    "biDanh": "remix",
    "trailer": "https://www.youtube.com/watch?v=At0SgaexXgo",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/remix_gp09.jpg",
    "moTa": "string",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2023-10-28T00:00:00",
    "danhGia": 9
  },
  {
    "maPhim": 11407,
    "tenPhim": "Jon C",
    "biDanh": "jon-c",
    "trailer": "https://www.youtube.com/watch?v=-OQYBmGySJQ",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/jon-c_gp09.jpg",
    "moTa": "a",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2023-11-01T00:00:00",
    "danhGia": 6
  },
  {
    "maPhim": 11408,
    "tenPhim": "adasdasd",
    "biDanh": "adasdasd",
    "trailer": "https://youtu.be/_iyC2aUCxY0",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/adasdasd_gp09.jpg",
    "moTa": "aaa",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2023-10-31T00:00:00",
    "danhGia": 8
  },
  {
    "maPhim": 11409,
    "tenPhim": "stringasdsx",
    "biDanh": "stringasdsx",
    "trailer": "string",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/stringasdsx_gp09.jpg",
    "moTa": "string",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2022-11-05T00:00:00",
    "danhGia": 0
  },
  {
    "maPhim": 11410,
    "tenPhim": "Remix Run",
    "biDanh": "remix-run",
    "trailer": "https://www.youtube.com/watch?v=TRWuZfv_8_I",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/remix-run_gp09.jpg",
    "moTa": "aaa",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2023-11-02T00:00:00",
    "danhGia": 7
  },
  {
    "maPhim": 11411,
    "tenPhim": "Remix 2",
    "biDanh": "remix-2",
    "trailer": "https://www.youtube.com/watch?v=TRWuZfv_8_I",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/remix-2_gp09.jpg",
    "moTa": "2",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2023-11-02T00:00:00",
    "danhGia": 5
  },
  {
    "maPhim": 11413,
    "tenPhim": "John Cena WWE",
    "biDanh": "john-cena-wwe",
    "trailer": "https://www.youtube.com/watch?v=hvSzRkz1SWE",
    "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/john-cena-wwe_gp09.jpg",
    "moTa": "Good film... 222!",
    "maNhom": "GP09",
    "ngayKhoiChieu": "2023-11-02T00:00:00",
    "danhGia": 9
  }
]
